language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Travis CI에서 빌드하여 만든 jar 파일을 AWS S3에 올릴 수 있도록 설정
#########################################################
# 배포에 불필요한 파일 제거를 위해 before_deploy 항목 수정
#########################################################
#before_deploy:
#  - zip -r freelec-springboot2-webservice *
#  - mkdir -p deploy
#  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip
before_deploy:
  - mkdir -p before-deploy  # zip에 포함시킬 파일들을 담기 위한 디렉토리 생성
  - cp scripts/*.sh before-deploy
  - cp appspec.yml before-deploy
  - cp build/libs/*.jar before-deploy
  - cd before-deploy && zip -r before-deploy *  # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip  # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY  # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY  # Travis repo settings에 설정된 값
    bucket: freelec-springboot2-webservice-s3 # AWS S3 버킷명
    region: ap-northeast-2
    skip_cleanup: true
    acl: private  # zip 파일 접근을 private 으로 설정
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY  # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY  # Travis repo settings에 설정된 값
    bucket: freelec-springboot2-webservice-s3 # AWS S3 버킷명
    key: freelec-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip  # 압축 확장자
    application: freelec-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: freelec-springboot2-webservice-deploy-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - chp320@naver.com
